import Header from '@/components/Header'
import './globals.css'
import { Montserrat } from 'next/font/google'
import Image from 'next/image'

const inter = Montserrat({ subsets: ['latin'] })

export const metadata = {
  title: 'Smart Home',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} max-h-screen h-screen relative overflow-y-hidden`}>
        <div className='bg-opacity-20 bg-black absolute w-full h-full backdrop-blur-xl z-[-1]' />
        <Image
          src='https://images.pexels.com/photos/2527248/pexels-photo-2527248.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1  '
          alt='Background image'
          fill
          className='z-[-2]'
        />
        <div className='absolute top-0 left-0 w-full z-1'><Header/></div>
        <div className='h-full z-2'>{children}</div>
      </body>
    </html>
  )
}
